package com.ishabaev.weather.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.ishabaev.weather.dao.OrmCity;
import com.ishabaev.weather.dao.OrmWeather;

import com.ishabaev.weather.dao.OrmCityDao;
import com.ishabaev.weather.dao.OrmWeatherDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig ormCityDaoConfig;
    private final DaoConfig ormWeatherDaoConfig;

    private final OrmCityDao ormCityDao;
    private final OrmWeatherDao ormWeatherDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        ormCityDaoConfig = daoConfigMap.get(OrmCityDao.class).clone();
        ormCityDaoConfig.initIdentityScope(type);

        ormWeatherDaoConfig = daoConfigMap.get(OrmWeatherDao.class).clone();
        ormWeatherDaoConfig.initIdentityScope(type);

        ormCityDao = new OrmCityDao(ormCityDaoConfig, this);
        ormWeatherDao = new OrmWeatherDao(ormWeatherDaoConfig, this);

        registerDao(OrmCity.class, ormCityDao);
        registerDao(OrmWeather.class, ormWeatherDao);
    }
    
    public void clear() {
        ormCityDaoConfig.getIdentityScope().clear();
        ormWeatherDaoConfig.getIdentityScope().clear();
    }

    public OrmCityDao getOrmCityDao() {
        return ormCityDao;
    }

    public OrmWeatherDao getOrmWeatherDao() {
        return ormWeatherDao;
    }

}
