package com.ishabaev.weather.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.ishabaev.weather.dao.City;
import com.ishabaev.weather.dao.Weather;

import com.ishabaev.weather.dao.CityDao;
import com.ishabaev.weather.dao.WeatherDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cityDaoConfig;
    private final DaoConfig weatherDaoConfig;

    private final CityDao cityDao;
    private final WeatherDao weatherDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cityDaoConfig = daoConfigMap.get(CityDao.class).clone();
        cityDaoConfig.initIdentityScope(type);

        weatherDaoConfig = daoConfigMap.get(WeatherDao.class).clone();
        weatherDaoConfig.initIdentityScope(type);

        cityDao = new CityDao(cityDaoConfig, this);
        weatherDao = new WeatherDao(weatherDaoConfig, this);

        registerDao(City.class, cityDao);
        registerDao(Weather.class, weatherDao);
    }
    
    public void clear() {
        cityDaoConfig.getIdentityScope().clear();
        weatherDaoConfig.getIdentityScope().clear();
    }

    public CityDao getCityDao() {
        return cityDao;
    }

    public WeatherDao getWeatherDao() {
        return weatherDao;
    }

}
